#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/agent-deck"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/agent-deck"
BIN_DIR="$HOME/.local/bin"
CONFIG_FILE="$CONFIG_DIR/host.env"
HOST_SCRIPT="$ROOT_DIR/scripts/agent-deck-host.sh"

say() { printf '%s\n' "$*"; }

fail() {
  say "Setup failed: $*" >&2
  exit 1
}

command -v node >/dev/null 2>&1 || fail "Node.js 24 LTS is required."
command -v corepack >/dev/null 2>&1 || fail "Corepack is required with Node.js 24 LTS."
command -v curl >/dev/null 2>&1 || fail "curl is required to verify the local OpenCode server."

node_major="$(node -p 'process.versions.node.split(".")[0]')"
(( node_major >= 24 )) || fail "Node.js 24 LTS or newer is required; found $(node --version)."

if ! command -v pnpm >/dev/null 2>&1; then
  corepack enable >/dev/null 2>&1 || fail "Could not enable pnpm with Corepack."
fi
command -v pnpm >/dev/null 2>&1 || fail "pnpm is required."

say "Installing workspace dependencies..."
pnpm install --frozen-lockfile
say "Building the Agent Deck host..."
pnpm build

has_opencode=0
has_codex=0
opencode_bin=""
codex_bin=""
existing_opencode_password=""
if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
  existing_opencode_password="${OPENCODE_SERVER_PASSWORD:-}"
  if [[ -n "${AGENT_DECK_OPENCODE_BIN:-}" && "${AGENT_DECK_OPENCODE_BIN}" != "$BIN_DIR/opencode" && -x "${AGENT_DECK_OPENCODE_BIN}" ]]; then
    opencode_bin="$AGENT_DECK_OPENCODE_BIN"
  fi
fi
if [[ -z "$opencode_bin" ]]; then
  detected_opencode="$(command -v opencode 2>/dev/null || true)"
  if [[ "$detected_opencode" == "$BIN_DIR/opencode" ]]; then
    if [[ -x "$BIN_DIR/opencode.before-agent-deck" ]]; then
      opencode_bin="$BIN_DIR/opencode.before-agent-deck"
    fi
  else
    opencode_bin="$detected_opencode"
  fi
fi
if [[ -n "$opencode_bin" && -x "$opencode_bin" ]]; then has_opencode=1; fi
if codex_bin="$(command -v codex 2>/dev/null)"; then has_codex=1; fi
(( has_opencode == 1 || has_codex == 1 )) || fail "Install OpenCode or Codex before running setup."

runtime=""
if (( has_opencode == 1 && has_codex == 1 )); then
  read -r -p "Runtime [opencode/codex] (opencode): " runtime
  runtime="${runtime:-opencode}"
elif (( has_opencode == 1 )); then
  runtime="opencode"
else
  runtime="codex"
fi
case "$runtime" in
  opencode) (( has_opencode == 1 )) || fail "OpenCode is not installed."; runtime_bin="$opencode_bin" ;;
  codex) (( has_codex == 1 )) || fail "Codex is not installed."; runtime_bin="$codex_bin" ;;
  *) fail "Choose opencode or codex." ;;
esac

default_workdir="$PWD"
read -r -p "Project directory [$default_workdir]: " workdir
workdir="${workdir:-$default_workdir}"
workdir="${workdir/#\~/$HOME}"
[[ -d "$workdir" ]] || fail "Project directory does not exist: $workdir"
workdir="$(CDPATH= cd -- "$workdir" && pwd)"

autostart="y"
read -r -p "Start Agent Deck automatically when you sign in? [Y/n]: " autostart_answer
autostart_answer="${autostart_answer:-$autostart}"
case "$autostart_answer" in
  [nN]*) autostart="n" ;;
  *) autostart="y" ;;
esac

detect_ip() {
  if command -v ipconfig >/dev/null 2>&1; then
    for device in en0 en1; do
      ip="$(ipconfig getifaddr "$device" 2>/dev/null || true)"
      [[ -n "$ip" ]] && { printf '%s' "$ip"; return; }
    done
  fi
  if command -v hostname >/dev/null 2>&1; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
    [[ -n "$ip" ]] && { printf '%s' "$ip"; return; }
  fi
  if command -v ip >/dev/null 2>&1; then
    ip="$(ip route get 1.1.1.1 2>/dev/null | awk '/src/ {for (i = 1; i <= NF; i++) if ($i == "src") print $(i + 1)}' | head -n1 || true)"
    [[ -n "$ip" ]] && { printf '%s' "$ip"; return; }
  fi
  printf '127.0.0.1'
}

bridge_interface="$(detect_ip)"
bridge_port="8765"
opencode_port="4096"
opencode_password="$existing_opencode_password"
if [[ -z "$opencode_password" ]]; then
  opencode_password="$(node -e 'console.log(require("node:crypto").randomBytes(32).toString("base64url"))')"
fi

mkdir -p "$CONFIG_DIR" "$STATE_DIR" "$BIN_DIR"

{
  printf '%s\n' '# Agent Deck host configuration. Generated by setup.sh.'
  printf 'AGENT_DECK_REPO=%q\n' "$ROOT_DIR"
  printf 'AGENT_DECK_RUNTIME=%q\n' "$runtime"
  printf 'AGENT_DECK_BRIDGE_INTERFACE=%q\n' "$bridge_interface"
  printf 'AGENT_DECK_BRIDGE_PORT=%q\n' "$bridge_port"
  printf 'AGENT_DECK_DB_PATH=%q\n' "$STATE_DIR/bridge.db"
  printf 'AGENT_DECK_LOG_DIR=%q\n' "$STATE_DIR"
  printf 'AGENT_DECK_NODE_BIN=%q\n' "$(command -v node)"
  printf 'AGENT_DECK_PNPM_BIN=%q\n' "$(command -v pnpm)"
  printf 'AGENT_DECK_RUNTIME_BIN=%q\n' "$runtime_bin"
  printf 'AGENT_DECK_OPENCODE_BIN=%q\n' "${opencode_bin:-}"
  printf 'OPENCODE_WORKDIR=%q\n' "$workdir"
  printf 'OPENCODE_SERVER_URL=%q\n' "http://127.0.0.1:$opencode_port"
  printf 'OPENCODE_SERVER_PORT=%q\n' "$opencode_port"
  printf 'OPENCODE_SERVER_USERNAME=%q\n' 'opencode'
  printf 'OPENCODE_SERVER_PASSWORD=%q\n' "$opencode_password"
} >"$CONFIG_FILE"
chmod 600 "$CONFIG_FILE"

ln -sfn "$HOST_SCRIPT" "$BIN_DIR/agent-deck-host"

if [[ "$runtime" == "opencode" ]]; then
  if [[ -e "$BIN_DIR/opencode" && ! -L "$BIN_DIR/opencode" ]]; then
    mv "$BIN_DIR/opencode" "$BIN_DIR/opencode.before-agent-deck"
    say "Moved existing $BIN_DIR/opencode to opencode.before-agent-deck."
  fi
  cat >"$BIN_DIR/opencode" <<'WRAPPER'
#!/usr/bin/env bash
set -euo pipefail
CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/agent-deck/host.env"
# shellcheck disable=SC1090
source "$CONFIG_FILE"

if [[ "${1:-}" == "--version" || "${1:-}" == "version" || "${1:-}" == "serve" || "${1:-}" == "attach" || "${1:-}" == "web" || "${1:-}" == "--help" ]]; then
  exec "$AGENT_DECK_OPENCODE_BIN" "$@"
fi

exec "$AGENT_DECK_OPENCODE_BIN" attach "$OPENCODE_SERVER_URL" \
  --dir "$PWD" \
  --username "$OPENCODE_SERVER_USERNAME" \
  --password "$OPENCODE_SERVER_PASSWORD" "$@"
WRAPPER
  chmod 755 "$BIN_DIR/opencode"
fi

profile=""
case "${SHELL##*/}" in
  zsh) profile="$HOME/.zshrc" ;;
  bash) profile="$HOME/.bashrc" ;;
esac
if [[ -n "$profile" ]]; then
  touch "$profile"
  if ! grep -Fq '# Agent Deck setup' "$profile"; then
    {
      printf '\n%s\n' '# Agent Deck setup'
      printf '%s\n' 'export PATH="$HOME/.local/bin:$PATH"'
    } >>"$profile"
  fi
fi

install_autostart() {
  case "$(uname -s)" in
    Darwin)
      label="com.agentdeck.host"
      plist="$HOME/Library/LaunchAgents/$label.plist"
      mkdir -p "$(dirname "$plist")"
      cat >"$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$label</string>
  <key>ProgramArguments</key>
  <array><string>$BIN_DIR/agent-deck-host</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$STATE_DIR/launchd.log</string>
  <key>StandardErrorPath</key><string>$STATE_DIR/launchd.log</string>
</dict>
</plist>
PLIST
      launchctl bootout "gui/$(id -u)/$label" >/dev/null 2>&1 || true
      launchctl bootstrap "gui/$(id -u)" "$plist"
      ;;
    Linux)
      if command -v systemctl >/dev/null 2>&1; then
        unit_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
        mkdir -p "$unit_dir"
        cat >"$unit_dir/agent-deck-host.service" <<UNIT
[Unit]
Description=Agent Deck host bridge
After=network-online.target

[Service]
ExecStart=$BIN_DIR/agent-deck-host
Restart=on-failure

[Install]
WantedBy=default.target
UNIT
        systemctl --user daemon-reload
        systemctl --user enable --now agent-deck-host.service
      else
        say "systemd not found; start $BIN_DIR/agent-deck-host from your session startup."
      fi
      ;;
    *)
      say "Automatic start is not configured for $(uname -s). Start $BIN_DIR/agent-deck-host manually."
      ;;
  esac
}

if [[ "$autostart" == "y" ]]; then
  install_autostart
else
  say "Automatic start skipped. Run $BIN_DIR/agent-deck-host when you want to connect."
fi

say ""
say "Agent Deck setup complete."
say "Runtime: $runtime"
say "Project: $workdir"
say "Bridge endpoint for phone: ws://$bridge_interface:$bridge_port"
say "Config: $CONFIG_FILE (permissions 600)"
say ""
say "Next steps:"
say "  1. Reload your shell: source ${profile:-your-shell-profile}"
say "  2. Open Agent Deck on your phone and tap Find Computers."
say "  3. Enter the pairing code printed in $STATE_DIR/bridge.log."
if [[ "$runtime" == "opencode" ]]; then
  say "  4. Run 'opencode' from the configured project directory; it will attach to the Agent Deck server."
fi
